version: '2'
services:
  mysql:
    image: mysql:5
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: your_db_password
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sqladmin
    ports:
      - "8081:80"
    links:
      - mysql:db
    restart: always

  encoder:
    image: leejoneshane/youphptube-encoder
    container_name: encoder
    environment:
      SITE_TITLE: PhpTube
      DOMAIN: your.domain
      DOMAIN_PROTOCOL: http
      ADMIN_EMAIL: me@test.com
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: your_db_password
      LANG: en
    ports:
      - "88:80"
      - "444:443"
    links:
      - mysql:db
    restart: always
  
  youphptube:
    image: leejoneshane/youphptube
    container_name: utube
    environment:
      SITE_TITLE: PhpTube
      DOMAIN: your.domain # we think maybe the domain name needs the port as well
      DOMAIN_PROTOCOL: http
      ADMIN_EMAIL: me@test.com
      ADMIN_PASSWORD: password 
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: your_db_password
      LANG: en
    ports:
      - "8001:80"
      - "8443:443"
    links:
      - mysql:db
    restart: always
